# Jupyter Notebook

**Możliwe działania**:

-	*uruchamianie kodu*: ikonka `▶` przy komórce / ikonka „Run” (na górze) / skrót klawiszowy `Shift + Enter` lub `Ctrl + Enter` (bez przejścia do kolejnego chunka)
-	*utworzenie nowej komórki*: ikonka `+` / skrót klawiszowy `b`
(kursor poza komórką – tryb poleceń (niebieska ramka komórki), a nie edycji (zielona); przejście do trybu poleceń poprzez kliknięcie poza pole komórki, ale nie za komórkę lub za pomocą skrótu klawiszowego `Esc`)
-	*zamiana typu komórki na komórkę z tekstem*: zmiana `Code` na `Markdown` / skrót klawiszowy `m`
-	*zamiana typu komórki na komórkę z kodem*: zmiana `Markdown` na `Code` / skrót klawiszowy `y`
-	*podzielenie komórki na dwie części*: `Ctrl + Shift + -`
-	*usunięcie komórki (jako wytnij/cut)*: ikonka `✂` / skrót klawiszowy `x`
-	*cofnięcie usunięcia komórki*: skrót klawiszowy `z`
-	*zmiana kolejności komórek*: ikonki `↑`, `↓`
-	*wyświetlenie informacji o funkcji*: skrót klawiszowy `Shift + Tab`
-	*lista pozostałych funkcji*: `Open the command palette`
-	*nowy plik*: np. w pliku `File` → `New Notebook` lub w folderze `New` → `Python 3`


**Ważne**:

 Komórki można uruchamiać w różnej kolejności.
 
 Wszystkie zmienne wczytane od pierwszego uruchomienia znajdują się w pamięci tzw. kernela.
 
 Do wyświetlenia zawartości ostatniej linii komórki nie potrzeba polecenia print, ale przy potrzebie wyświetlenia kilku linii komórki jest ono konieczne.

## Ćwiczenie

In [ ]:
'Hello world!', 2 + 3     # Uruchom komórkę.

Uruchom tę komórkę, a poniżej dodaj komórkę z kodem oraz komórkę z tekstem.

Usuń tę komórkę.

Tę też usuń.

Przywróć ostatnią usuniętą komórkę.

Zamień kolejnością tą komórkę z poprzednią.

## Podstawy Markdowna

-	nowa linia (`\` na końcu poprzedniej linii)
-	nowy akapit (pusta linia przed)
-	nagłówki (1. poziom: `#` przed tekstem nagłówka lub podkreślenie tekstu nagłówka przez `=` w kolejnej linii, 2. poziom: `##` lub podkreślenie przez `-`)
-	pogrubienie (`**`)
-	kursywa (`*`)
-	lista numerowana (`1. … 2. … 3. …` w kolejnych liniach)
-	lista nienumerowana (`- … - … - …` w kolejnych liniach)


## Nieco szerzej o podstawach Markdowna

Nowy wiersz w markdownie można utworzyć przez backslash \
lub dwie  
spacje.

Nowy akapit tworzymy pozostawiając pusty wiersz.

  Domyślnie akapity nie posiadają wcięcia, nawet jeśli użyjemy tabulacji.

W taki sposób robimy w markdownie:

*kursywę*,          _też kursywę_, \
**pogrubienie**,    __też pogrubienie__, \
~~przekreślenie~~.

> Gdy chcemy wyróżnić jakiś tekst,
>
> możemy go wyeksponować przez znak ">".

Trzy kreski 

---

lub trzy gwiazdki

***

albo trzy podkreślenia

___

pozwalają zrobić poziomą linię.

---

Rozdział 1
===========

Podkreślenie znakami "=" daje nagłówek najwyższego poziomu.

Podrozdział 1.1
----------------

Podkreślenie znakami "-" daje nagłówek niższego poziomu.

Podrozdział 1.2
----------------

[Jakiś tekst.]


# Rozdział 2

Jeden znak "#" daje ten efekt co "=" - nagłówek najwyższego poziomu.

## Podrozdział 2.1

Dwa znaki "#" dają ten efekt co "-" - nagłówek niższego poziomu.

### Podpodrozdział 2.1.1
 
Trzy znaki "#" pozwalają na nagłówek jeszcze niższego poziomu.\
liczba znaków "#" = poziom zagłębienia nagłówka (nie jego rozmiar)
 
### Podpodrozdział 2.1.2

Nagłówki wykonane przez znaki "=" i "-" oraz przez znak "#" można bez problemu łączyć.

---

### Elementy do dodania

**Lista numerowana**

1. dodajemy
1. wypisując
4. kolejne
3. liczby

**Lista nienumerowana**

- dodajemy
  + poprzez
+ znaki takie jak:
  - myślniki
  + plusy
  * i gwiazdki
- oraz
  * odpowiednią
      * do poziomu
        * liczbę
  * tabulacji

Możemy

1. łączyć
    - oba
      * typy
2. list


Myślniki ("-") oraz pionowe linie ("|") pozwalają na

| utworzenie | tabelki. |
|------------|----------|
| komórka    | komórka  |
| komórka    | komórka  |


Możemy też dodać tekst sformatowany jako kod, np. **pseudokod**. Pozwala na to 

    wcięcie
    z dwoma
    tabulacjami.
    
Będzie on jedynie sformatowany jako kod, więc nie będzie wykonywał się podczas kompilacji pliku.
    
Taki sam efekt uzyskamy umieszczając treść pomiędzy

```
trzema backtickami
z obu stron.
```

Pojedynczy `backtick` z obu stron pozwala na umieszczenie kodu w wierszu, pomiędzy tekstem.

# NumPy

NumPy (**Num**erical **Py**thon) – biblioteka do operacji na tablicach liczbowych różnego wymiaru (macierzy wielowymiarowych), wykorzystywanych często w obliczeniach inżynierskich.

NumPy dostarcza listy „ulepszone” pod względem dostępnych możliwości, szybkości operacji i wydajności przechowywania, co ułatwia bardziej złożone obliczenia. 

Instalacja pakietu - w wierszu poleceń:

```
   pip install numpy
```

## Lista vs Numpy.array

### Macierz jednowymiarowa

In [4]:
print([5, 2, 7, 1])               # lista w pakiecie base (wbudowanego)

[5, 2, 7, 1]

In [84]:
import numpy as np                # załadowanie pakietu

print(np.array([5, 2, 7, 1]))     # lista w pakiecie numpy 

[5 2 7 1]


In [74]:
lista = [5, 2, 7, 1]  

print(type(lista))
print(type(np.array(lista)))

<class 'list'>
<class 'numpy.ndarray'>


In [76]:
lista = [5, 'a', 7, 1]  

print(lista)
print(np.array(lista))            # zmiana int->str - numpy.array nie może składać się z elementów różnego typu!

[5, 'a', 7, 1]
['5' 'a' '7' '1']


### Macierz dwuwymiarowa

In [17]:
print([[6, 4,  18],                # tablica w pakiecie base
       [3, 27, 8]])

[[6, 4, 18], [3, 27, 8]]

In [83]:
print(np.array([[6, 4,  18],
                [3, 27, 8]]))      # tablica w pakiecie numpy 

[[ 6  4 18]
 [ 3 27  8]]


In [53]:
tablica = [[6, 4,  18],
           [3, 27, 8]]

print(len(tablica))
print(np.array(tablica).shape)

2
(2, 3)


In [82]:
tablica = [[6, 4,  18],
           [3, 27]]

print(tablica)
print(np.array(tablica))   # numpy.array musi mieć wszystkie rzędy i kolumny tej samej długości!

[[6, 4, 18], [3, 27]]
[list([6, 4, 18]) list([3, 27])]


C:\Users\Agnieszka\AppData\Local\Temp\ipykernel_10076\2679396505.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(tablica))


### Macierz wielowymiarowa

In [80]:
tablica = [[[0, 6], [8, 7],  [8, 1]],
           [[2, 2], [7, 4],  [1, 3]]]

print(tablica)
print(np.array(tablica))

[[[0, 6], [8, 7], [8, 1]], [[2, 2], [7, 4], [1, 3]]]
[[[0 6]
  [8 7]
  [8 1]]

 [[2 2]
  [7 4]
  [1 3]]]


In [81]:
print(len(tablica))
print(np.array(tablica).shape)

2
(2, 3, 2)


### Ustalenie typu elementów macierzy

In [100]:
lista = [5, 2, 7, 1] 

print(lista)
print(np.array(lista))
print(np.array(lista, dtype = np.float32))
print()
print(type(lista[0]))
print(np.array(lista).dtype)                   # liczby całkowite   / zmienna ilościowa dyskretna
print(np.array(lista, dtype = float).dtype)    # liczby rzeczywiste / zmienna ilościowa ciągła

[5, 2, 7, 1]
[5 2 7 1]
[5. 2. 7. 1.]

<class 'int'>
int32
float64


In [106]:
print(np.array(lista, dtype = 'int16'))       # różnica niewidoczna, ale jest ona w dokładności liczby zapisanej w pamięci (liczbie bitów, na których jest zapisana)
print(np.array(lista, dtype = 'int32'))
print(np.array(lista, dtype = 'int64'))

print(np.array(lista, dtype = 'float16'))
print(np.array(lista, dtype = 'float32'))
print(np.array(lista, dtype = 'float64'))

[5 2 7 1]
[5 2 7 1]
[5 2 7 1]
[5. 2. 7. 1.]
[5. 2. 7. 1.]
[5. 2. 7. 1.]


## Operacje na Numpy.array

### Operacje na listach


Wykonywanie operacji na obiektach numpy.array polega na wykonywania ich na odpowiadających sobie elementach tych obiektów. \
Muszą więc być one tych samych wymiarów.

In [167]:
lista1 = [1, 2, 3]
lista2 = [2, 3, 4]
nmp_lista1 = np.array(lista1)
nmp_lista2 = np.array(lista2)

print(nmp_lista1 + nmp_lista2)
print(nmp_lista1 - nmp_lista2)
print(nmp_lista1 * nmp_lista2)
print(nmp_lista1 ** nmp_lista2)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[ 1  8 81]


In [149]:
print(lista1 + lista2)          # inne działanie dla list - konkatenacja list
print(lista1 * lista2)          # brak działania dla list

[1, 2, 3, 2, 3, 4]


TypeError: can't multiply sequence by non-int of type 'list'

In [150]:
print([l1 + l2 for l1, l2 in zip(lista1, lista2)])  # działające dla list, ale dłuższe
print([l1 * l2 for l1, l2 in zip(lista1, lista2)])

[3, 5, 7]
[2, 6, 12]


### Operacje na tablicach

In [168]:
nmp_tablica1 = np.array([[6, 4,  18],
                         [3, 27, 8]])
nmp_tablica2 = np.array([[7, 1, 5],
                         [9, 3, 8]])

print(nmp_tablica1 + nmp_tablica2)
print(nmp_tablica1 - nmp_tablica2)
print(nmp_tablica1 * nmp_tablica2)
print(nmp_tablica1 ** nmp_tablica2)

[[13  5 23]
 [12 30 16]]
[[-1  3 13]
 [-6 24  0]]
[[42  4 90]
 [27 81 64]]
[[  279936        4  1889568]
 [   19683    19683 16777216]]


### Mnożenie macierzy

Uwaga! W przypadku list operacje dodawania, odejmowania i mnożenia zgadzają się z matematycznymi operacjami na wektorach, ale w przypadku tablic, matematyczne mnożenie macierzy oznacza co innego!

In [152]:
nmp_macierz1 = np.array([[6, 4],
                         [3, 27]])
nmp_macierz2 = np.array([[7, 1],
                         [9, 3]])

print(nmp_macierz1 @ nmp_macierz2)        # co innego!

[[ 78  18]
 [264  84]]


### Broadcasting

Broadcasting to wykonanie operacji na liczbie i obiekcie numpy.array, co polega na wykonaniu jej dla każdego elementu tego obiektu i tej liczby.

In [169]:
print(nmp_lista1)
print(nmp_lista1 + 2)
print(nmp_lista1 - 2)
print(nmp_lista1 * 2)
print(nmp_lista1 ** 2)

[1 2 3]
[3 4 5]
[-1  0  1]
[2 4 6]
[1 4 9]


In [170]:
print(nmp_tablica1)
print(nmp_tablica1 + 2)
print(nmp_tablica1 - 2)
print(nmp_tablica1 * 2)
print(nmp_tablica1 ** 2)

[[ 6  4 18]
 [ 3 27  8]]
[[ 8  6 20]
 [ 5 29 10]]
[[ 4  2 16]
 [ 1 25  6]]
[[12  8 36]
 [ 6 54 16]]
[[ 36  16 324]
 [  9 729  64]]


In [173]:
print(nmp_tablica1)
print(nmp_tablica1 + np.array([[2, 2, 2],     # to samo!
                               [2, 2, 2]])) 
print(nmp_tablica1 - np.array([[2, 2, 2],    
                               [2, 2, 2]])) 
print(nmp_tablica1 * np.array([[2, 2, 2],     
                               [2, 2, 2]])) 
print(nmp_tablica1 ** np.array([[2, 2, 2],     
                                [2, 2, 2]])) 

[[ 6  4 18]
 [ 3 27  8]]
[[ 8  6 20]
 [ 5 29 10]]
[[ 4  2 16]
 [ 1 25  6]]
[[12  8 36]
 [ 6 54 16]]
[[ 36  16 324]
 [  9 729  64]]


Można to rozszerzyć:

In [182]:
print(nmp_tablica1)
print(nmp_tablica1 + np.array([[2],
                               [4]])) 
print(nmp_tablica1 + np.array([[2, 2, 2],     # to samo!
                               [4, 4, 4]]))

(2, 3)
(2, 1)
[[ 6  4 18]
 [ 3 27  8]]
[[ 8  6 20]
 [ 7 31 12]]
[[ 8  6 20]
 [ 7 31 12]]


### Konkatenacja

In [371]:
nmp_tablica1 = np.array([[1, 2, 3],
                         [4, 5, 6]])
nmp_tablica2 = np.array([[7,  8,  9],
                         [10, 11, 12]])
nmp_tablica3 = np.array([[13, 14, 15],
                         [16, 17, 18]])

wide_tablica = np.hstack([nmp_tablica1, nmp_tablica2, nmp_tablica3])
long_tablica = np.vstack([nmp_tablica1, nmp_tablica2, nmp_tablica3])
print(wide_tablica)
print(long_tablica)

[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


**Modyfikacja wymiaru tablicy**:

In [372]:
print(wide_tablica.reshape(3, 6))
print(long_tablica.reshape(3, 6))

[[ 1  2  3  7  8  9]
 [13 14 15  4  5  6]
 [10 11 12 16 17 18]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


## Indeksowanie i slicing

### Indeksowanie na listach

In [215]:
lista = [5, 3, 6, 2, 4]
nmp_lista = np.array(lista)

print(lista[1])
print(nmp_lista[1])

print(lista[-2])
print(nmp_lista[-2])

3
3
2
2


In [216]:
print(type(lista[1]))
print(type(nmp_lista[1]))

<class 'int'>
<class 'numpy.int32'>


### Slicing na listach

In [213]:
lista = [5, 3, 6, 2, 4]

print(lista[1:4])
print(nmp_lista[1:4])

print(lista[-3:-1])
print(nmp_lista[-3:-1])

print(lista[1:])
print(nmp_lista[1:])

print(lista[:4])
print(nmp_lista[:4])

print(lista[:])
print(nmp_lista[:])

[3, 6, 2]
[3 6 2]
[6, 2]
[6 2]
[3, 6, 2, 4]
[3 6 2 4]
[5, 3, 6, 2]
[5 3 6 2]
[5, 3, 6, 2, 4]
[5 3 6 2 4]


In [217]:
print(type(lista[1:4]))
print(type(nmp_lista[1:4]))

<class 'list'>
<class 'numpy.ndarray'>


### Indeksowanie i slicing na tablicach

**Indeksowanie**

In [225]:
tablica = [[6, 4,  18, 3,  2],
           [3, 27, 8,  10, 0],
           [1, 9,  5,  7,  6]]
nmp_tablica = np.array(tablica)

print(tablica[1][2])
print(nmp_tablica[1, 2])

print(tablica[1][-2])
print(nmp_tablica[1, -2])

8
8
10
10


**Slicing**

In [230]:
print(tablica[1:])
print(tablica[1:][2:])       # nie zadziała!
print(nmp_tablica[1:, 2:])

[[3, 27, 8, 10, 0], [1, 9, 5, 7, 6]]
[]
[[ 8 10  0]
 [ 5  7  6]]


In [231]:
print(tablica[:2])
print(tablica[:2][:-2])      # nie zadziała!
print(nmp_tablica[:2, :-2])

[[6, 4, 18, 3, 2], [3, 27, 8, 10, 0]]
[]
[[ 6  4 18]
 [ 3 27  8]]


---

### Ćwiczenia

1. Utwórz listę numpy.array składającą się z sześcianów kolejnych cyfr (0-9).

2. Przy pomocy slicingu, wybierz z poniższej tablicy cyfry 5, 6, 8, 9.

In [241]:
nmp_tablica = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])



3. Przy pomocy slicingu, wybierz z poniższej tablicy cyfry 6, 7, 10, 11.

In [242]:
nmp_tablica2 = np.array([[1, 2,  3,  4],
                         [5, 6,  7,  8],
                         [9, 10, 11, 12]])



---

## Filtrowanie

### Operacje logiczne na Numpy.array

Funkcje logiczne:

- == - równa się
- != - nie równa się
- $>$ - większe
- $<$ - mniejsze
- $>$= - większe równe
- $<$= - mniejsze równe
- ~  - negacja
- &  - koniunkcja
- |  - alternatywa

In [294]:
nmp_lista1 = np.array([5, 3, 6, 2, 4])
nmp_lista2 = np.array([5, 3, 4, 2, 1])
nmp_lista3 = np.array([1, 2, 3, 4, 5])

print(nmp_lista1 == nmp_lista2)
print(nmp_lista1 != nmp_lista2)
print(nmp_lista1 > nmp_lista3)
print(nmp_lista1 >= 3)
print((nmp_lista1 >= 3) & (nmp_lista1 < 5))

[ True  True False  True False]
[False False  True False  True]
[ True  True  True False False]
[ True  True  True False  True]
[False  True False False  True]


In [387]:
lista1 = [5, 3, 6, 2, 4]
lista2 = [5, 3, 5, 4, 5]
lista3 = [5, 3, 7, 4, 5]

print(lista1 > lista2)        # inne działanie dla list! - porównanie podobne do porównania 2 liczb
print(lista1 > lista3)
print(lista1 > 3)             # brak działania dla list

True
False


TypeError: '>' not supported between instances of 'list' and 'int'

### Filtrowanie

**filtrowanie** - slicing przy pomocy listy wartości logicznych przypisanych do kolejnych indeksów

`True` - wybranie elementu \
`False` - niewybranie elementu

In [275]:
print(nmp_lista1)
print(nmp_lista1 > 3)
print(nmp_lista1[nmp_lista1 > 3])

[5 3 6 2 4]
[ True False  True False  True]
[5 6 4]


## Modyfikacja

In [290]:
nmp_lista = np.array([5, 3, 6, 2, 4])
print(nmp_lista)

nmp_lista[1] = -44
nmp_lista[3:] = 99

print(nmp_lista)

[5 3 6 2 4]
[  5 -44   6  99  99]


In [295]:
nmp_lista[(nmp_lista >= 1) & (nmp_lista < 10)] = 11

print(nmp_lista)

[ 11 -44  11  99  99]


## Utworzenie kopii

In [237]:
lista1 = [5, 3, 6, 2, 4]
lista2 = lista1
lista3 = lista1[:]

lista1[1] = 99

print(lista1)
print(lista2)    # nie działa!
print(lista3)    # działa 

[5, 99, 6, 2, 4]
[5, 99, 6, 2, 4]
[5, 3, 6, 2, 4]


In [240]:
nmp_lista1 = np.array([5, 3, 6, 2, 4])
nmp_lista2 = nmp_lista1
nmp_lista3 = nmp_lista1[:]
nmp_lista4 = nmp_lista1.copy()              # funkcja kopiująca

nmp_lista1[1] = 99

print(nmp_lista1)     
print(nmp_lista2)     # nie działa!
print(nmp_lista3)     # nie działa!
print(nmp_lista4) 

[ 5 99  6  2  4]
[ 5 99  6  2  4]
[ 5 99  6  2  4]
[5 3 6 2 4]


---

### Ćwiczenie

Utwórz listę podobną do poniższej, ale jeśli pojawiają się w niej liczby mniejsze równe 0, to pomnóż je razy 5. \
Uwaga! Nie modyfikuj bezpośrednio podanej listy.

In [305]:
nmp_lista1 = np.array([5, -1, 3, 6, 0, -1, 2, 4, 1])



---

## Funkcje tabularyczne

In [346]:
print(np.arange(1, 20, 2))    # ciąg liczb rzeczywistych od 1 do 19 o kroku 2
print(np.arange(0, 1, 0.1))

[ 1  3  5  7  9 11 13 15 17 19]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [347]:
print(range(1, 20, 2))
print(range(0, 1, 0.1))       # base.range nie pozwala na ciągi liczb rzeczywistych, jedynie całkowitych

range(1, 20, 2)


TypeError: 'float' object cannot be interpreted as an integer

In [348]:
print(np.linspace(0, 1, 5))             # ciąg 5 liczb rzeczywistych rozciągniętych równo na przedziale [0, 1]

[0.   0.25 0.5  0.75 1.  ]


In [349]:
print(np.zeros(5))                      # lista zer długości 5

[0. 0. 0. 0. 0.]


In [350]:
print(np.zeros((3, 4)))                 # tablica zer wymiaru 3 x 4

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [351]:
print(np.ones(5))                       # lista jedynek długości 5

[1. 1. 1. 1. 1.]


In [352]:
print(np.ones((3, 4)))                  # tablica jedynek wymiaru 3 x 4

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [353]:
print(np.random.randint(1, 10, 5))      # lista 5 losowych liczb całkowitych z przedziału [1, 10]

[9 2 5 7 6]


In [354]:
print(np.random.randint(1, 10, (3, 4))) # tablica 3 x 4 losowych liczb całkowitych z przedziału [1, 10]

[[9 9 3 1]
 [6 2 6 4]
 [5 3 4 6]]


In [355]:
print(np.random.rand(5))                # lista 5 liczb losowych z przedziału [0, 1)

[0.83050154 0.68759507 0.24436539 0.95880074 0.55562047]


In [356]:
print(np.random.rand(3, 4))             # tablica 3 x 4 liczb losowych z przedziału [0, 1) 

[[0.57379901 0.9116156  0.42214495 0.81373062]
 [0.2690298  0.31401804 0.73768209 0.89371737]
 [0.11668406 0.61858708 0.68241852 0.81323798]]


In [357]:
print(np.random.randn(5))               # lista 5 liczb losowych ze standardowego rozkładu normalnego (N(0, 1))

[-1.99511056 -0.33610861 -0.26738307  1.36783183  1.44817551]


In [358]:
print(np.random.randn(3, 4))            # tablica 3 x 4  liczb losowych ze standardowego rozkładu normalnego (N(0, 1))

[[ 1.68917856  1.0716927   0.37099594  2.49586064]
 [ 0.81170729 -1.25901863  0.89145444  0.20596665]
 [ 2.48524567 -1.06888454 -0.70028515 -1.90080628]]


## Funkcje matematyczne

In [378]:
nmp_tablica = np.random.rand(3, 4)    

print(np.round(nmp_tablica, 2))     # zaokrąglenie dla każdego elementu

array([[0.06246344, 0.99969324, 0.64824604, 0.50913287],
       [0.31002676, 0.64965507, 0.57823257, 0.18524079],
       [0.96425016, 0.89460427, 0.78235014, 0.51946109]])

In [379]:
nmp_tablica = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

print(np.sqrt(nmp_tablica))         # pierwiastek dla każdego elementu

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [385]:
nmp_tablica = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.mean(nmp_tablica))
print(np.std(nmp_tablica))          # statystyki dla elementów tablicy jako próby, np. średnia, odchylenie standardowe

5.0
2.581988897471611
